# Generated by Django 3.1.7 on 2021-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=500)),
                ('display_picture', models.FileField(upload_to='')),
            ],
        ),
    ]
