# Generated by Django 3.1.7 on 2021-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210313_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
